"""Initial schema with all tables and features

Revision ID: 001_initial_schema
Revises: 
Create Date: 2025-09-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table with all final features
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('auth_id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('User', 'Admin', name='roleenum'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Create entities table with all final features
    op.create_table(
        'entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('string_field', sa.String(), nullable=False),
        sa.Column('int_field', sa.Integer(), nullable=False),
        sa.Column('enum_field', sa.Enum('A', 'B', 'C', 'D', name='entityenum'), nullable=False),
        sa.Column('string_array_field', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('bool_field', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create simple_entities table with all final features
    op.create_table(
        'simple_entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('string_field', sa.String(), nullable=False),
        sa.Column('int_field', sa.Integer(), nullable=False),
        sa.Column('enum_field', sa.Enum('A', 'B', 'C', 'D', name='simpleentityenum'), nullable=False),
        sa.Column('string_array_field', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('bool_field', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
