"""Add cascade delete to Driver and Admin

Revision ID: a1b2c3d4e5f6
Revises: eb010a6ed5ad
Create Date: 2026-02-08 00:31:30.165149

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '01f342ea9ad6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admin_info_user_id_fkey'), 'admin_info', type_='foreignkey')
    op.create_foreign_key(None, 'admin_info', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('drivers_user_id_fkey'), 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(op.f('drivers_user_id_fkey'), 'drivers', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'admin_info', type_='foreignkey')
    op.create_foreign_key(op.f('admin_info_user_id_fkey'), 'admin_info', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
