"""Add location mappings table

Revision ID: 0833d1329b8b
Revises: 789dc643b9c0
Create Date: 2025-11-08 00:21:30.287411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0833d1329b8b'
down_revision = '789dc643b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mapping_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=True),
    sa.Column('mapping_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_mappings')
    # ### end Alembic commands ###
