"""Move address from user to driver

Revision ID: 2fb89d48dba8
Revises: 988258439eae
Create Date: 2025-11-17 02:00:55.534425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '2fb89d48dba8'
down_revision = '988258439eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('drivers', 'address')
    # ### end Alembic commands ###
