"""make_auth_id_nullable_and_add_user_invites

Revision ID: 4971451d79cd
Revises: c7d9e2b14a06
Create Date: 2026-05-31 22:47:34.113186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4971451d79cd'
down_revision = 'c7d9e2b14a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('user_invite_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_invite_id')
    )
    op.create_index(op.f('ix_user_invites_user_id'), 'user_invites', ['user_id'], unique=True)
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_invites_user_id'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
