"""Add created_at updated_at to route_groups

Revision ID: 5244c9e0440d
Revises: 002_initial_db_migration
Create Date: 2025-10-22 22:22:00.752087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5244c9e0440d'
down_revision = '002_initial_db_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('route_groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_groups', 'updated_at')
    op.drop_column('route_groups', 'created_at')
    # ### end Alembic commands ###
