"""Add place_id to location model

Revision ID: 55b817a0ac96
Revises: 0833d1329b8b
Create Date: 2025-11-09 00:50:10.490765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '55b817a0ac96'
down_revision = '0833d1329b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column(
        'place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'place_id')
    # ### end Alembic commands ###
