"""add announcement_last_reads and drop note_chain_reads

Revision ID: 58e90e6bdd92
Revises: 595032f5ede7
Create Date: 2026-04-05 10:04:11.974467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58e90e6bdd92'
down_revision = '595032f5ede7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_last_reads',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('announcement_last_read_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_last_read_id'),
    sa.UniqueConstraint('user_id', name='uq_announcement_last_reads_user')
    )
    op.drop_table('note_chain_reads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_chain_reads',
    sa.Column('note_chain_read_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_chain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_chain_id'], ['note_chains.note_chain_id'], name=op.f('note_chain_reads_note_chain_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('note_chain_reads_user_id_fkey')),
    sa.PrimaryKeyConstraint('note_chain_read_id', name=op.f('note_chain_reads_pkey')),
    sa.UniqueConstraint('note_chain_id', 'user_id', name=op.f('uq_note_chain_reads_chain_user'))
    )
    op.drop_table('announcement_last_reads')
    # ### end Alembic commands ###
