"""make auth_id nullable and create user_invites table

Revision ID: 5b1f33614790
Revises: 8b03ae4022cd
Create Date: 2026-03-29 00:10:52.944793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b1f33614790'
down_revision = '8b03ae4022cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('user_invite_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_invite_id')
    )
    op.create_index(op.f('ix_user_invites_user_id'), 'user_invites', ['user_id'], unique=True)
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_invites_user_id'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
