"""add state to locations

Revision ID: 692d84fc21be
Revises: 0c05ebddd50b
Create Date: 2026-03-31 01:47:11.602521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '692d84fc21be'
down_revision = '0c05ebddd50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('state', sa.String(), nullable=False, server_default='ACTIVE'))
    op.alter_column('locations', 'state', server_default=None)
    op.alter_column('routes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('locations', 'state')
    # ### end Alembic commands ###
