"""Update location mapping table

Revision ID: 789dc643b9c0
Revises: 7af7d4689b08
Create Date: 2025-11-06 00:05:43.272618

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789dc643b9c0'
down_revision = '7af7d4689b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column(
        'state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'state')
    # ### end Alembic commands ###
