"""Fix location model

Revision ID: 7af7d4689b08
Revises: 003_add_polylines
Create Date: 2025-10-14 20:57:24.833586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af7d4689b08'
down_revision = '003_add_polylines'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'dietary_restrictions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('locations', 'is_school')
    op.add_column('route_groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('route_groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_groups', 'updated_at')
    op.drop_column('route_groups', 'created_at')
    op.add_column('locations', sa.Column('is_school', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('locations', 'dietary_restrictions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
