"""add announcements table

Revision ID: 88d4ec63dfb5
Revises: 8b03ae4022cd
Create Date: 2026-03-20 09:07:19.767435

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '88d4ec63dfb5'
down_revision = '8b03ae4022cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_index(op.f('ix_announcements_announcement_id'), 'announcements', ['announcement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_announcement_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
