"""remove completed field on driver_assignment

Revision ID: 8b03ae4022cd
Revises: eb010a6ed5ad
Create Date: 2026-02-11 01:22:55.339927

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8b03ae4022cd'
down_revision = 'eb010a6ed5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_assignments', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_assignments', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
