"""Add locations mapping table

Revision ID: 9e693c4553f7
Revises: afbf8fe1a1a3
Create Date: 2025-12-15 03:30:11.090772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9e693c4553f7'
down_revision = 'afbf8fe1a1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_delivery_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_boxes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('halal', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    sa.Column('dietary_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_mapping_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('location_mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_mappings')
    # ### end Alembic commands ###
