"""Add polyline fields to routes table

Revision ID: 8574dd773368
Revises: afbf8fe1a1a3
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8574dd773368'
down_revision = 'afbf8fe1a1a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column(
        'encoded_polyline', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))
    op.add_column('routes', sa.Column(
        'polyline_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'polyline_updated_at')
    op.drop_column('routes', 'encoded_polyline')
    # ### end Alembic commands ###

