"""Add place ID to locations table

Revision ID: afbf8fe1a1a3
Revises: 7af7d4689b08
Create Date: 2025-12-01 01:19:25.636934

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'afbf8fe1a1a3'
down_revision = '7af7d4689b08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column(
        'place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'place_id')
    # ### end Alembic commands ###
