"""Add route group id to driver assignments

Revision ID: b1c2d3e4f5a6
Revises: afbf8fe1a1a3
Create Date: 2025-12-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'afbf8fe1a1a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('driver_assignments', sa.Column(
        'route_group_id', sa.Uuid(), nullable=True))
    
    # Populate route_group_id from route_group_memberships for existing assignments
    # This finds the route_group_id for each driver_assignment based on its route_id
    op.execute("""
        UPDATE driver_assignments da
        SET route_group_id = (
            SELECT rgm.route_group_id
            FROM route_group_memberships rgm
            WHERE rgm.route_id = da.route_id
            LIMIT 1
        )
        WHERE da.route_group_id IS NULL
    """)
    
    # Now make it non-nullable
    op.alter_column('driver_assignments', 'route_group_id', nullable=False)
    
    # Create foreign key constraint
    op.create_foreign_key(
        'fk_driver_assignments_route_group_id',
        'driver_assignments',
        'route_groups',
        ['route_group_id'],
        ['route_group_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_driver_assignments_route_group_id', 'driver_assignments', type_='foreignkey')
    op.drop_column('driver_assignments', 'route_group_id')
    # ### end Alembic commands ###

