"""make auth_id nullable

Revision ID: b57f6ad88485
Revises: 8b03ae4022cd
Create Date: 2026-03-17 23:33:31.602012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b57f6ad88485'
down_revision = '8b03ae4022cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
