"""update_user_system

Revision ID: ba76119b3e4c
Revises: b1c2d3e4f5a6
Create Date: 2025-11-24 01:25:48.941556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'ba76119b3e4c'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'system_settings' not in existing_tables:
        op.create_table('system_settings',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('default_cap', sa.Integer(), nullable=True),
        sa.Column('route_start_time', sa.Time(), nullable=True),
        sa.Column('warehouse_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('warehouse_longitude', sa.Float(), nullable=True),
        sa.Column('warehouse_latitude', sa.Float(), nullable=True),
        sa.Column('system_settings_id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('system_settings_id')
        )

    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('auth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
        )
        op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)

    # Check existing columns in admin_info
    admin_info_columns = [col['name'] for col in inspector.get_columns('admin_info')]

    if 'receive_email_notifications' not in admin_info_columns:
        op.add_column('admin_info', sa.Column('receive_email_notifications', sa.Boolean(), nullable=False, server_default='true'))

    if 'user_id' not in admin_info_columns:
        # Migrate existing admin_info records to users table
        connection = op.get_bind()

        # Get existing admin records that need migration
        if 'admin_email' in admin_info_columns and 'admin_name' in admin_info_columns:
            existing_admins = connection.execute(sa.text("""
                SELECT admin_id, admin_name, admin_email, auth_id
                FROM admin_info
            """)).fetchall()

            # Create user records for existing admins
            for admin in existing_admins:
                user_id = admin[0]  # Use admin_id as user_id for consistency
                connection.execute(sa.text("""
                    INSERT INTO users (user_id, name, email, auth_id, role, created_at, updated_at)
                    VALUES (:user_id, :name, :email, :auth_id, 'admin', NOW(), NOW())
                    ON CONFLICT DO NOTHING
                """), {
                    'user_id': user_id,
                    'name': admin[1],
                    'email': admin[2],
                    'auth_id': admin[3] if admin[3] else f'admin_{user_id}'
                })

        # Add user_id column as nullable first
        op.add_column('admin_info', sa.Column('user_id', sa.Uuid(), nullable=True))

        # Populate user_id with admin_id for existing records
        connection.execute(sa.text("""
            UPDATE admin_info SET user_id = admin_id WHERE user_id IS NULL
        """))

        # Now make it NOT NULL
        op.alter_column('admin_info', 'user_id', nullable=False)

    op.create_unique_constraint(None, 'admin_info', ['user_id'])
    op.create_foreign_key(None, 'admin_info', 'users', ['user_id'], ['user_id'])

    # Drop columns only if they exist
    if 'admin_name' in admin_info_columns:
        op.drop_column('admin_info', 'admin_name')
    if 'default_cap' in admin_info_columns:
        op.drop_column('admin_info', 'default_cap')
    if 'route_start_time' in admin_info_columns:
        op.drop_column('admin_info', 'route_start_time')
    if 'warehouse_location' in admin_info_columns:
        op.drop_column('admin_info', 'warehouse_location')
    if 'admin_email' in admin_info_columns:
        op.drop_column('admin_info', 'admin_email')

    # Check existing columns in drivers
    drivers_columns = [col['name'] for col in inspector.get_columns('drivers')]

    if 'user_id' not in drivers_columns:
        # Migrate existing driver records to users table
        connection = op.get_bind()

        # Get existing driver records that need migration
        if 'email' in drivers_columns and 'name' in drivers_columns:
            existing_drivers = connection.execute(sa.text("""
                SELECT driver_id, name, email, auth_id
                FROM drivers
            """)).fetchall()

            # Create user records for existing drivers
            for driver in existing_drivers:
                user_id = driver[0]  # Use driver_id as user_id for consistency
                connection.execute(sa.text("""
                    INSERT INTO users (user_id, name, email, auth_id, role, created_at, updated_at)
                    VALUES (:user_id, :name, :email, :auth_id, 'driver', NOW(), NOW())
                    ON CONFLICT DO NOTHING
                """), {
                    'user_id': user_id,
                    'name': driver[1],
                    'email': driver[2],
                    'auth_id': driver[3] if driver[3] else f'driver_{user_id}'
                })

        # Add user_id column as nullable first
        op.add_column('drivers', sa.Column('user_id', sa.Uuid(), nullable=True))

        # Populate user_id with driver_id for existing records
        connection.execute(sa.text("""
            UPDATE drivers SET user_id = driver_id WHERE user_id IS NULL
        """))

        # Now make it NOT NULL
        op.alter_column('drivers', 'user_id', nullable=False)

    # Drop indexes only if they exist
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('drivers')]
    if 'ix_drivers_auth_id' in existing_indexes:
        op.drop_index(op.f('ix_drivers_auth_id'), table_name='drivers')
    if 'ix_drivers_email' in existing_indexes:
        op.drop_index(op.f('ix_drivers_email'), table_name='drivers')

    op.create_unique_constraint(None, 'drivers', ['user_id'])
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['user_id'])

    # Drop columns only if they exist
    if 'name' in drivers_columns:
        op.drop_column('drivers', 'name')
    if 'email' in drivers_columns:
        op.drop_column('drivers', 'email')
    if 'auth_id' in drivers_columns:
        op.drop_column('drivers', 'auth_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('auth_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_auth_id'), 'drivers', ['auth_id'], unique=True)
    op.drop_column('drivers', 'user_id')
    op.add_column('admin_info', sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('admin_info', sa.Column('warehouse_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('route_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('default_cap', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('admin_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('admin_info', 'user_id')
    op.drop_column('admin_info', 'receive_email_notifications')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
