"""update_user_system

Revision ID: ba76119b3e4c
Revises: 7af7d4689b08
Create Date: 2025-11-24 01:25:48.941556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'ba76119b3e4c'
down_revision = '7af7d4689b08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('default_cap', sa.Integer(), nullable=True),
    sa.Column('route_start_time', sa.Time(), nullable=True),
    sa.Column('warehouse_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warehouse_longitude', sa.Float(), nullable=True),
    sa.Column('warehouse_latitude', sa.Float(), nullable=True),
    sa.Column('system_settings_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('system_settings_id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.add_column('admin_info', sa.Column('receive_email_notifications', sa.Boolean(), nullable=False))
    op.add_column('admin_info', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'admin_info', ['user_id'])
    op.create_foreign_key(None, 'admin_info', 'users', ['user_id'], ['user_id'])
    op.drop_column('admin_info', 'admin_name')
    op.drop_column('admin_info', 'default_cap')
    op.drop_column('admin_info', 'route_start_time')
    op.drop_column('admin_info', 'warehouse_location')
    op.drop_column('admin_info', 'admin_email')
    op.add_column('drivers', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_drivers_auth_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.create_unique_constraint(None, 'drivers', ['user_id'])
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['user_id'])
    op.drop_column('drivers', 'name')
    op.drop_column('drivers', 'email')
    op.drop_column('drivers', 'auth_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('auth_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_auth_id'), 'drivers', ['auth_id'], unique=True)
    op.drop_column('drivers', 'user_id')
    op.add_column('admin_info', sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('admin_info', sa.Column('warehouse_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('route_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('default_cap', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admin_info', sa.Column('admin_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('admin_info', 'user_id')
    op.drop_column('admin_info', 'receive_email_notifications')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
