"""location state

Revision ID: bb9e2e8439ad
Revises: 01f342ea9ad6
Create Date: 2026-03-08 00:25:47.157162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9e2e8439ad'
down_revision = '01f342ea9ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_mappings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_mappings',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location_delivery_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num_boxes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('halal', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('dietary_restrictions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location_mapping_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mapping_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('location_mapping_id', name=op.f('location_mappings_pkey'))
    )
    # ### end Alembic commands ###
