"""add input payload, error message and summary columns to jobs

Revision ID: d4eefe397549
Revises: bc7876e56dd1
Create Date: 2026-07-28 02:26:20.612153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4eefe397549'
down_revision = 'bc7876e56dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('input_payload', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('routes_created', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('total_stops', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('total_distance_km', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('total_families', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'total_families')
    op.drop_column('jobs', 'total_distance_km')
    op.drop_column('jobs', 'total_stops')
    op.drop_column('jobs', 'routes_created')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'input_payload')
    # ### end Alembic commands ###
