"""added ends_at_warehouse to route model

Revision ID: eb010a6ed5ad
Revises: 7af7d4689b08
Create Date: 2025-12-01 00:31:47.827096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb010a6ed5ad'
down_revision = 'ba76119b3e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('ends_at_warehouse', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'ends_at_warehouse')
    # ### end Alembic commands ###
