"""add location state

Revision ID: f0588853da2b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 20:16:50.819884

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0588853da2b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_mappings', sa.Column('mapping_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('locations', sa.Column('state', sa.VARCHAR(), nullable=False, server_default='ACTIVE'))
    op.alter_column('routes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('locations', 'state')
    op.drop_column('location_mappings', 'mapping_name')
    # ### end Alembic commands ###
